---
title: Ben Groulx
email: ben@bengroulx.com
description: Ben Groulx is a user interface designer and front-end developer living and working out of Vancouver, Canada.

timezone: America/Los_Angeles
collections:
    posts:
        title: Posts
        output: true
    uploads:
        title: Uploads
        output: true
twitter:
    username: bengroulx
url:
    username: bengroulx
baseurl:
include:
    - _pages
permalink: "/:title/"
markdown: kramdown
gems:
    - jekyll-assets
    - octopress-autoprefixer
