# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site Settings
title: Ben Groulx
email: ben@bengroulx.com
twitter_username: bengroulx
github_username:  bengroulx
description: > # this means to ignore newlines until "url:"
    Ben Groulx is a user interface designer and front-end developer living and
    working out of Vancouver, Canada.

# URL - The base hostname & protocol for your site
url: "http://bengroulx.github.io"
username: bengroulx

# Base URL - The subpath of your site, e.g. /blog
baseurl: ""

# Build Settings
markdown: kramdown
gems:
  - octopress-autoprefixer
