---
title: Ben Groulx
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: ben@bengroulx.com
description: Ben Groulx is a user interface designer and front-end developer living
  and working out of Vancouver, Canada.
twitter:
  username: bengroulx
permalink: "/:title/"
url: 
baseurl: 
markdown: kramdown
gems:
- jekyll-assets
- jekyll-seo-tag
- octopress-minify-html
- octopress-autoprefixer
include:
- _pages
exclude:
- node_modules
assets:
  compress:
    css: true
    js: true
sass:
  style: compressed
