---
title: Ben Groulx
timezone: America/Los_Angeles
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: ben@bengroulx.com
description: Ben Groulx is a user interface designer and front-end developer living
  and working out of Vancouver, Canada.
twitter:
  username: bengroulx
url: 
username: bengroulx
baseurl: 
include:
- _pages
permalink: "/:title/"
markdown: kramdown
gems:
- octopress-autoprefixer
